2020-03-19 09:50:35,998 - instabot version: 0.115.0 (bot) - INFO - Instabot version: 0.115.0 Started
2020-03-19 09:50:35,999 - instabot version: 0.115.0 (bot) - DEBUG - Bot imported from /usr/local/lib/python2.7/dist-packages/instabot/bot/bot.pyc
2020-03-19 09:50:36,003 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-19 09:50:36,004 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-19 09:50:36,004 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/nurchuliss_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=d2ae494d-2f06-4681-a48b-9c921cf0c11b
- uuid=423e6931-be2b-4a9b-9c1b-4d8fe19b14e6
- client_session_id=268a5428-7d0f-4843-a15d-ae9fbc5e3936
- device_id=android-19c11c9b12e66074
2020-03-19 09:50:36,005 - instabot version: 0.115.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: False
2020-03-19 09:50:36,484 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [400]>
2020-03-19 09:50:36,485 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/timeline/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:36,485 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:36,485 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:36,486 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:36,850 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [400]>
2020-03-19 09:50:36,851 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/reels_tray/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:36,852 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:36,852 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:36,853 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:37,222 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: direct_v2/ranked_recipients/ returned response: <Response [400]>
2020-03-19 09:50:37,222 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/direct_v2/ranked_recipients/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:37,222 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:37,224 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:37,224 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:37,609 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: direct_v2/ranked_recipients/ returned response: <Response [400]>
2020-03-19 09:50:37,611 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/direct_v2/ranked_recipients/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:37,612 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:37,612 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:37,612 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:38,017 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: direct_v2/inbox/ returned response: <Response [400]>
2020-03-19 09:50:38,018 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/direct_v2/inbox/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:38,018 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:38,018 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:38,018 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:38,370 - instabot version: 0.115.0 (api) - DEBUG - GET to endpoint: direct_v2/get_presence/ returned response: <Response [400]>
2020-03-19 09:50:38,371 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/direct_v2/get_presence/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:38,371 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:38,371 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:38,371 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:38,749 - instabot version: 0.115.0 (api) - DEBUG - GET to endpoint: news/inbox/?limited_activity=true&show_su=true returned response: <Response [400]>
2020-03-19 09:50:38,749 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/news/inbox/%253Flimited_activity%253Dtrue%2526show_su%253Dtrue", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:38,749 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:38,750 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:38,751 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:39,116 - instabot version: 0.115.0 (api) - DEBUG - GET to endpoint: users/profile_notice/ returned response: <Response [400]>
2020-03-19 09:50:39,116 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/users/profile_notice/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:39,117 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:39,117 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:39,118 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:39,519 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: discover/explore/ returned response: <Response [400]>
2020-03-19 09:50:39,519 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/discover/explore/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:39,519 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:39,520 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:39,521 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:39,524 - instabot version: 0.115.0 (api) - INFO - Login flow failed, the cookie is broken. Relogin again.
2020-03-19 09:50:39,525 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-19 09:50:39,526 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-19 09:50:39,527 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/nurchuliss_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=d2ae494d-2f06-4681-a48b-9c921cf0c11b
- uuid=423e6931-be2b-4a9b-9c1b-4d8fe19b14e6
- client_session_id=01a3aec0-d952-4d18-8a32-324f2993d0dd
- device_id=android-19c11c9b12e66074
2020-03-19 09:50:39,527 - instabot version: 0.115.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-19 09:50:39,957 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2020-03-19 09:50:39,958 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/get_prefill_candidates/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:39,958 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:39,958 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:39,958 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:40,388 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [400]>
2020-03-19 09:50:40,388 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/qe/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:40,388 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:40,389 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:40,389 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:40,760 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [400]>
2020-03-19 09:50:40,760 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/launcher/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:40,760 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:40,762 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:40,762 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:41,195 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [400]>
2020-03-19 09:50:41,196 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/contact_point_prefill/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:41,196 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:41,198 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:41,198 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:41,625 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-03-19 09:50:41,625 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/login/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-19 09:50:41,625 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-19 09:50:41,626 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-19 09:50:41,626 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-19 09:50:41,626 - instabot version: 0.115.0 (api) - ERROR - Failed to login go to instagram and change your password
2020-03-19 09:50:41,627 - instabot version: 0.115.0 (api) - INFO - Username or password is incorrect.
