2020-03-25 22:13:33,894 - instabot version: 0.115.0 (bot) - INFO - Instabot version: 0.115.0 Started
2020-03-25 22:13:33,895 - instabot version: 0.115.0 (bot) - DEBUG - Bot imported from /usr/local/lib/python2.7/dist-packages/instabot/bot/bot.pyc
2020-03-25 22:13:33,896 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-25 22:13:33,898 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-25 22:13:33,899 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=58f5fd4f-f694-43c5-a410-2c4a9174485e
- device_id=android-d13a49bfddbe7ce7
2020-03-25 22:13:33,899 - instabot version: 0.115.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: False
2020-03-25 22:13:34,433 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [400]>
2020-03-25 22:13:34,433 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/timeline/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:34,433 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:34,435 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:34,435 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:35,080 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [400]>
2020-03-25 22:13:35,082 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/reels_tray/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:35,082 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:35,082 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:35,083 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:35,084 - instabot version: 0.115.0 (api) - INFO - Login flow failed, the cookie is broken. Relogin again.
2020-03-25 22:13:35,087 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-25 22:13:35,089 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-25 22:13:35,089 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=58f5fd4f-f694-43c5-a410-2c4a9174485e
- device_id=android-d13a49bfddbe7ce7
2020-03-25 22:13:35,091 - instabot version: 0.115.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-25 22:13:35,605 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2020-03-25 22:13:35,607 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/get_prefill_candidates/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:35,607 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:35,607 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:35,608 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:36,188 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [400]>
2020-03-25 22:13:36,188 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/qe/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:36,188 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:36,189 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:36,190 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:36,952 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [400]>
2020-03-25 22:13:36,953 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/launcher/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:36,955 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:36,955 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:36,955 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:37,481 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [400]>
2020-03-25 22:13:37,481 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/contact_point_prefill/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:37,481 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:37,482 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:37,482 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:38,059 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-03-25 22:13:38,059 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/login/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:38,059 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:38,060 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:38,060 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:38,060 - instabot version: 0.115.0 (api) - ERROR - Failed to login go to instagram and change your password
2020-03-25 22:13:38,060 - instabot version: 0.115.0 (api) - INFO - Username or password is incorrect.
2020-03-25 22:13:46,861 - instabot version: 0.115.0 (bot) - INFO - Instabot version: 0.115.0 Started
2020-03-25 22:13:46,862 - instabot version: 0.115.0 (bot) - DEBUG - Bot imported from /usr/local/lib/python2.7/dist-packages/instabot/bot/bot.pyc
2020-03-25 22:13:46,864 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-25 22:13:46,865 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-25 22:13:46,865 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=58f5fd4f-f694-43c5-a410-2c4a9174485e
- device_id=android-d13a49bfddbe7ce7
2020-03-25 22:13:46,866 - instabot version: 0.115.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: False
2020-03-25 22:13:47,387 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [400]>
2020-03-25 22:13:47,387 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/timeline/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:47,387 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:47,389 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:47,391 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:47,978 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [400]>
2020-03-25 22:13:47,980 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/feed/reels_tray/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:47,980 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:47,982 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:47,983 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:47,984 - instabot version: 0.115.0 (api) - INFO - Login flow failed, the cookie is broken. Relogin again.
2020-03-25 22:13:47,987 - instabot version: 0.115.0 (api_login) - DEBUG - Loading cookies
2020-03-25 22:13:47,988 - instabot version: 0.115.0 (api_login) - DEBUG - Loading uuids
2020-03-25 22:13:47,988 - instabot version: 0.115.0 (api_login) - INFO - Recovery from /var/www/html/example.com/public_html/cron/insta/config/menabungtanah_uuid_and_cookie.json: COOKIE True - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=a30092fa-e99d-46c6-b2c6-a80dfd9fe9e9
- uuid=8aacbd94-8261-42c3-ae0d-d5476e870db9
- client_session_id=58f5fd4f-f694-43c5-a410-2c4a9174485e
- device_id=android-d13a49bfddbe7ce7
2020-03-25 22:13:47,991 - instabot version: 0.115.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-03-25 22:13:48,423 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2020-03-25 22:13:48,425 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/get_prefill_candidates/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:48,425 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:48,426 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:48,426 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:48,898 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [400]>
2020-03-25 22:13:48,898 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/qe/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:48,898 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:48,899 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:48,899 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:49,462 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [400]>
2020-03-25 22:13:49,463 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/launcher/sync/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:49,463 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:49,466 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:49,467 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:50,651 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [400]>
2020-03-25 22:13:50,651 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/contact_point_prefill/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:50,652 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:50,652 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:50,652 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:51,176 - instabot version: 0.115.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-03-25 22:13:51,176 - instabot version: 0.115.0 (api) - DEBUG - Responsecode indicates error; response content: {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/?next=/api/v1/accounts/login/", "api_path": "/challenge/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail"}
2020-03-25 22:13:51,176 - instabot version: 0.115.0 (api) - ERROR - Request returns 400 error!
2020-03-25 22:13:51,177 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: challenge_required
2020-03-25 22:13:51,177 - instabot version: 0.115.0 (api) - INFO - Instagram's error message: {}
2020-03-25 22:13:51,177 - instabot version: 0.115.0 (api) - ERROR - Failed to login go to instagram and change your password
2020-03-25 22:13:51,178 - instabot version: 0.115.0 (api) - INFO - Username or password is incorrect.
